[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
erased-serde = "0.4.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"
